"""
Regression tests for the parked/for-sale domain classification fix.

Incident: parked/for-sale registrar landers (Sedo, GoDaddy Domains, Afternic, etc.) were
being written to MongoDB as status='dead', both via the heuristic classify() short-circuit
AND (more consequentially) via fetcher.py / runner.py / known_gambling_runner.py /
recheck_batch.py / api/routers/domains.py, which all independently treated any parked-marker
match as a dead-domain signal upstream of classify() ever running. Per spec: a domain that is
reachable and rendering a parked/for-sale lander is not gambling and not dead — it must be
'regular'.

These tests only exercise pure functions (classifier.classify, fetcher._classify_failure) —
no MongoDB, Ollama, or Playwright required.

Run with: pytest tests/test_parked_domain_status.py -v
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from checking_url.classifier import classify, load_keywords

KW = load_keywords()

PARKED_HTML_SAMPLES = [
    """<html><title>royalbet888.com is for sale</title><body>
    This domain is for sale. Buy this domain now or make an offer.
    Powered by Sedo Domain Parking.
    </body></html>""",
    """<html><title>Domain Parking</title><body>
    This webpage was generated by the domain owner using Sedo Domain Parking.
    Related Searches: casino, betting, poker
    </body></html>""",
    """<html><body>The domain <b>casinowin888.bet</b> is available for purchase.
    Inquire about this domain or make an offer today. domainmarket.com
    </body></html>""",
]


def test_parked_for_sale_lander_classifies_as_regular_not_dead():
    """Core requirement: a parked/for-sale domain lander must classify() to 'regular',
    even though the raw text is stuffed with gambling-adjacent domain names/keywords."""
    for html in PARKED_HTML_SAMPLES:
        decision, hits = classify(html, KW, url="https://example-parked-domain.bet")
        assert decision == "regular", (
            f"parked lander misclassified as {decision!r} instead of 'regular': {html[:80]!r}"
        )


def test_fetcher_distinguishes_parked_from_true_dead():
    """fetcher._classify_failure must return a distinct 'parked' failure_type for
    parked/for-sale marker matches, separate from 'dead_confirmed' (true 404, no lander
    content) — these are downstream-mapped to 'regular' vs 'dead' respectively."""
    try:
        from checking_url.fetcher import _classify_failure
    except ImportError as e:
        import unittest
        raise unittest.SkipTest(
            f"fetcher.py's dependency (scrapling) not installed in this environment: {e}"
        )

    parked_body = "<html><body>This domain is for sale. Buy this domain. sedo.com</body></html>"
    true_dead_body = "<html><body>404 Not Found</body></html>"

    # 404 status code but body is a parking lander -> 'parked', not 'dead_confirmed'
    assert _classify_failure(status_code=404, html=parked_body) == "parked"

    # 404 status code with no parked markers -> genuinely dead
    assert _classify_failure(status_code=404, html=true_dead_body) == "dead_confirmed"

    # 200 status with parked markers in body -> 'parked'
    assert _classify_failure(status_code=200, html=parked_body) == "parked"

    # No html, no status, no error -> falls through to connection_failed, never 'dead_confirmed'
    # (dead_confirmed is reserved for a real, confirmed 404)
    assert _classify_failure(status_code=None, html=None, error=None) == "connection_failed"

    # Blocked markers still take priority over parked markers if somehow both present
    blocked_and_parked = "<html><body>Checking your browser... this domain is for sale</body></html>"
    assert _classify_failure(status_code=200, html=blocked_and_parked) == "blocked"
