"""
checking_url/classifier.py — Direct keyword matching classifier.

Loads keywords directly from gambling_top_500_keywords.json.
Rule: If >= 3 keywords are found in page HTML, site is marked as gambling.
"""
import json
from pathlib import Path
from bs4 import BeautifulSoup

# Path to the 500 keywords JSON file
KEYWORDS_FILE = Path(__file__).resolve().parent.parent / "gambling_top_500_keywords.json"


def load_keywords() -> set:
    """Load keywords from gambling_top_500_keywords.json into a set."""
    if KEYWORDS_FILE.exists():
        with open(KEYWORDS_FILE, "r", encoding="utf-8") as f:
            terms = json.load(f)
            kw_set = set(str(kw).strip().lower() for kw in terms if kw)
            print(f"[classifier] Loaded {len(kw_set)} keywords from {KEYWORDS_FILE.name}")
            return kw_set
    print(f"[classifier WARNING] {KEYWORDS_FILE.name} not found!")
    return set()


def _extract_text(html: str) -> str:
    """Return visible text + title + meta description, lowercased."""
    soup = BeautifulSoup(html, 'html.parser')
    for tag in soup(["script", "style"]):
        tag.decompose()
    parts = [soup.get_text(separator=' ')]
    title = soup.find('title')
    if title and title.string:
        parts.append(title.string)
    for meta in soup.find_all('meta', attrs={'name': True, 'content': True}):
        if meta['name'].lower() in ('description', 'keywords'):
            parts.append(meta['content'])
    return ' '.join(parts).lower()


# Common markers for parked domains, domain marketplaces, and for-sale landers
PARKED_AND_FOR_SALE_MARKERS = [
    # Domain sales phrases
    "is for sale",
    "domain for sale",
    "this domain is for sale",
    "this domain is available for sale",
    "the domain name is available for sale",
    "domain is available for purchase",
    "buy this domain",
    "purchase this domain",
    "purchase domain",
    "inquire about this domain",
    "make an offer on this domain",
    "make an offer",
    "domain portfolio for sale",
    "this domain may be for sale",
    "premium domain for sale",
    "domain name marketplace",
    "domain broker",
    "fast domain transfers",
    "domain name has been registered",
    "domain is registered at",
    "get this domain",
    "bid on this domain",
    "buy now",
    
    # Parking & placeholder phrases
    "domain parking",
    "domain is parked",
    "parked domain",
    "parked by",
    "parked free, courtesy of",
    "this webpage was generated by the domain owner using sedo",
    "this page is parked free",
    "this domain is registered and parked",
    "welcome to the future home of",
    "website coming soon",
    "under construction",
    "domain expired",
    "domain renewal",
    
    # Marketplace and parking platforms
    "domains.atom.com",
    "atom.com",
    "dan.com",
    "sedo.com",
    "sedoparking.com",
    "afternic.com",
    "hugedomains.com",
    "squadhelp.com",
    "undeveloped.com",
    "domainmarket.com",
    "bodis.com",
    "parkingcrew.net",
    "parkingcrew.com",
    "sav.com",
    "above.com",
    "brandpa.com",
    "brandbucket.com",
    "buydomains.com",
    "domainagent.com",
    "godaddy.com/domains",
    "namecheap.com/domains",
    "dynadot.com",
    "epik.com",
    "uniregistry.com",
    "voodoo.com",
    "domainnameshop.com",
]

# Negative archetype indicators: generalized patterns that indicate non-gambling domains
# (Prevents false positives from SEO spam injected on educational, e-commerce, or media sites)
NEGATIVE_ARCHETYPES = {
    "educational": [
        "admission", "facult", "academic", "syllabus", "curriculum", 
        "degree college", "undergraduate", "postgraduate", "ph.d",
        "examination result", "chancellor", "principal", "alumni", "merit list"
    ],
    "ecommerce": [
        "add to cart", "shopping cart", "buy now", "in stock", "out of stock",
        "free shipping", "return policy", "customer reviews", "product description",
        "delivery charges", "order summary", "secure checkout", "payment options"
    ],
    "news_media_wiki": [
        "breaking news", "editorial team", "journalism", "press release",
        "published by", "fandom wiki", "community wiki", "table of contents"
    ],
}

HIGH_INTENT_GAMBLING_TERMS = {
    "online casino", "live casino", "sportsbook", "poker room", 
    "real money casino", "aviator crash game", "betting app", 
    "slot machine", "live dealer", "deposit bonus"
}


def is_parked_or_for_sale(text: str, html: str = "", url: str = "") -> tuple[bool, list[str]]:
    """Check if the page is a parked domain, domain-for-sale lander, or marketplace."""
    text_lower = text.lower() if text else ""
    html_lower = html.lower() if html else ""
    url_lower = url.lower() if url else ""

    matched_markers = []
    for marker in PARKED_AND_FOR_SALE_MARKERS:
        if marker in text_lower or marker in html_lower or marker in url_lower:
            matched_markers.append(marker)

    if matched_markers:
        return True, matched_markers
    return False, []


def detect_negative_archetype(text: str) -> tuple[bool, str]:
    """Detect if the page is predominantly an educational, e-commerce, or news/wiki site."""
    text_lower = text.lower() if text else ""
    
    for archetype, signals in NEGATIVE_ARCHETYPES.items():
        matched = [s for s in signals if s in text_lower]
        if len(matched) >= 2:
            return True, f"{archetype}_site (signals: {', '.join(matched[:3])})"
            
    return False, ""


def classify(html: str, url: str = "", keywords: set = None, min_keywords: int = 3) -> tuple[bool, list[str]]:
    """Generalized High-Accuracy Classifier:
    - Checks for parked/for-sale domain landers.
    - Evaluates negative archetypes (educational, e-commerce, media) to defeat SEO spam injections.
    - Performs multi-keyword & high-intent structural gambling verification.
    - Zero hardcoded domain lists!
    """
    if not html:
        return False, ["empty_html"]

    text = _extract_text(html)

    # 1. Parked / For-Sale Check
    is_parked, parked_reasons = is_parked_or_for_sale(text=text, html=html, url=url)
    if is_parked:
        return False, [f"excluded:parked_or_for_sale ({', '.join(parked_reasons[:3])})"]

    kw_set = keywords if keywords is not None else load_keywords()

    # 2. Match gambling keywords
    matched = [kw for kw in kw_set if kw in text]

    # 3. Negative Archetype Check (Educational, E-Commerce, News/Wiki)
    is_negative, neg_reason = detect_negative_archetype(text)
    if is_negative:
        # If page is clearly educational/e-commerce/news, only mark as gambling if there is an overwhelmingly high density of gambling terms (>= 8)
        if len(matched) < 8:
            return False, [f"excluded:{neg_reason}"]

    # 4. Gambling Decision Logic:
    # Requires at least min_keywords (default 3) OR at least 2 keywords if one is a High-Intent Gambling Term
    has_high_intent = any(kw in matched for kw in HIGH_INTENT_GAMBLING_TERMS)
    
    is_gambling = (len(matched) >= min_keywords) or (len(matched) >= 2 and has_high_intent)
    return is_gambling, matched

